version: '3'

services:
    promo-manager:
        container_name: promo-manager
        hostname: promo-manager
        image: dev-it/promo-manager:latest
        expose:
          - 8081
        ports:
          - 8081:8081
        networks:
          - devit-network
        environment:
          - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
          - spring.cloud.config.label=master
          - spring.profiles.active=docker
          - USER_CONFIGURATION_SERVER=uservice
          - PASSWORD_CONFIGURATION_SERVER=password
        links:
          - mongodb:mongodb
        depends_on:
          - configuration-server
          - eureka
          - zuul
          - mongodb
          - zookeeper
          - kafka
        logging:
            driver: json-file

networks:
    devit-network:
        driver: bridge