mongo:
  config:
    replicaSetName:
    type: INSTANCE
    connectTimeout: 3000
    socketTimeout: 3000
    serverTimeout: 3000
    retry:
      retryBackOffTime: 5000
      retryMaxAttempts: 3

server:
  port: 8081

cxf:
  path: /promoManager/v1
